### ISSUE TITLE
Top Insets are not applied correctly on device view for API < 30

### ISSUE THREAD

**Issue by Moustachauve** [Moustachauve/WLED-Native-Android#13]
![image](https://github.com/Moustachauve/WLED-Native-Android/assets/2206577/6050eb57-95ba-416b-90c5-c44313905b4c)

**Comment by Kolan04** [comment]
What exactly is not working properly for you?

It would be great to set the timer not only for 60 minutes, but for different times.

**Comment by Moustachauve** [comment]
A new version with a brand new UI is rolling out. It should fully fix this. Feel free to re-open if this is still a new issue with the new version.
