### ISSUE TITLE
Takes too long for the toggle buttons to appear

### ISSUE THREAD

**Issue by Andro-Marian** [Moustachauve/WLED-Native-Android#23]
On main page some Toggle Buttons takes way too long to appear.
Like 5-6 seconds to appear when going back of when refreshing the page.

Not sure what is doing but should be instant.

I think has some updates checking, should not disturb this anyway.

Also, would be nice a option to stop checking for updates automatically.

**Comment by Moustachauve** [comment]
There was a bug with the handling of the callback from the device updating. The next major version of the app will fix this.

**Comment by Moustachauve** [comment]
The new version is rolling out. Feel free to re-open if this is still a new issue with the new version.
