### ISSUE TITLE
Add a way to customize the colors manually

### ISSUE THREAD

**Issue by Andro-Marian** [Moustachauve/WLED-Native-Android#25]
There should be a way to customize the colors manually.
And the offline devices should be darker in color.

**Comment by Moustachauve** [comment]
The UI has been completely updated in the next upcoming version of the app, you might enjoy it. It does make offline devices appear in a darker colour.

**Comment by Moustachauve** [comment]
The new version is rolling out! Feel free to reopen if you feel like this is still needed with the new UI.
