### ISSUE TITLE
Show the device list instead of "Select a device" screen

### ISSUE THREAD

**Issue by slangreck** [Moustachauve/WLED-Native-Android#26]
When I open the app I'm often greeted by a screen telling me to "Select a device from the list". I think this happens mostly after the phone lost Wi-Fi connection while the app was in the background, but I'm not sure.

This forces me to press back to actually get to the list, where I can then select a device. I think it would be far better to get rid of this screen and show the list directly when whatever triggers this screen happens. It would be even better if the app would just try to reconnect to the last selected device, so I don't have to select it again.

**Comment by Moustachauve** [comment]
This is fixed in the upcoming version of the app. Be on the lookout for an update soon!

**Comment by slangreck** [comment]
Awesome, thank you!

**Comment by Moustachauve** [comment]
The new version is rolling out!
