### ISSUE TITLE
Is the FOSS branch still maintained?

### ISSUE THREAD

**Issue by JonnyTech** [Moustachauve/WLED-Native-Android#30]
After v5 was realeased last week in the Play Store, will there be a FOSS build either on F-droid or GitHub releases?

**Comment by Moustachauve** [comment]
V5 is still in beta. However, FOSS was needed because the main branch used to contain some libraries like Google firebase. V5 got rid of that, so the FOSS branch and the regular branch are now the same!

**Comment by JonnyTech** [comment]
Ah, thanks. I saw a v5 release but did not see that it was a beta. Will you still submit a tag for a f-droid build so us non play store users get an update?

**Comment by Moustachauve** [comment]
I will, once it is stable. It should be soon

**Comment by Moustachauve** [comment]
https://github.com/Moustachauve/WLED-Native-Android/releases/tag/v5.0.0 has the apk available
