### ISSUE TITLE
Device that was offline can't be controlled once it comes back online.

### ISSUE THREAD

**Issue by Moustachauve** [Moustachauve/WLED-Native-Android#4]
Discord user "AI LIFE" reported this issue:

>  I've found some bug with ur app when device go offline it show the unable to connect picture but when it's back online it didn't reload even if at hone page I can control it the UI still didn't load

**Comment by JTWTMN** [comment]
I am having similar issue. Galaxy S22 on Android 13. App finds the device but when it is selected the UI will not load. If I go into settings and toggle "automatically discover new devices" or "show offline devices last" ON or Off the UI will load. I enabled logging so maybe you will receive them.

**Comment by Moustachauve** [comment]
The latest update should fix this issue. There is also now a manual refresh button.
