### ISSUE TITLE
WLED UI doesn't appear for device

### ISSUE THREAD

**Issue by Yash-Garg** [Moustachauve/WLED-Native-Android#5]
I've tried removing the device and re adding it but the WLED UI doesn't show up.

It works if I reinstall the application and open it, but again has the same issue if I close and reopen the application.

<img src="https://user-images.githubusercontent.com/33605526/207314296-60c37ce0-8070-466a-b4a0-79e7a5540a25.png" height=800 /> <img src="https://user-images.githubusercontent.com/33605526/207314310-77c90046-bd3c-4f60-9aff-6a1015efa864.png" height=800 />

**Comment by JTWTMN** [comment]
My app does the same thing, once the device is discovered if i go into settings and toggle "automatically discover new devices" or "show offline devices last" ON or Off the UI will load.

**Comment by Moustachauve** [comment]
The latest update that is rolling out right now should be fixing this issue :)
