### ISSUE TITLE
Device shows for some seconds, then lost completely

### ISSUE THREAD

**Issue by natrius** [Moustachauve/WLED-Native-Android#8]
Device: Xiaomi Mi 9
    OS: Android 10
    Version: 2.2.5 F-Droid

So it seems to find a device but it gets lost immediately. If i'm fast enough, i can press on the device and open it but it never gets saved, so i have to search every time. 

When searching manually via IP (its available in browser on the smartphone) it seems to not find anything at all. 

I add two screenshots and the second one is 4 seconds after the first one. 

![wled_1_signal-2023-10-06-112803_002](https://github.com/Moustachauve/WLED-Native-Android/assets/7243447/cc00c607-af9d-4dde-b1c7-5328e669a72f)
![wled_2_signal-2023-10-06-112803_003](https://github.com/Moustachauve/WLED-Native-Android/assets/7243447/077c3909-130a-45fb-b27b-e044254c97f7)

**Comment by Moustachauve** [comment]
Is it possible you have hidden the device? Can you check in the top left menu, then "manage device" to see if you see anything? 

I'll investigate the bug on my side too!

**Comment by natrius** [comment]
Its empty. "You don't have any devices yet"

**Comment by Moustachauve** [comment]
@natrius  do you still have this issue in the latest versions (4.0.0 and above) ?

**Comment by natrius** [comment]
Add the github-repository and installed 4.1.1 and now the strip show up all the time, even with deactivated WLAN. Thanks for working on it!
