### ISSUE TITLE
Is there any API info for the App?

### ISSUE THREAD

**Issue by vortigont** [Moustachauve/WLED-Native-Android#9]
Hi!
Is there any API info for this App available? I have my own wled-like project that mimics WLED discovery, but it does not work with this app.
I know that WLED makes http request to `/win` and expects an xml document with keys `<ac>`, `<ds>` etc...
But this app does not work like that. I see in tcpdump that it requests `/json/si` but have no idea what should be a reply there for the lamp to be discoverable.
Any hints would be appreciated!

**Comment by Moustachauve** [comment]
Hey @vortigont !

The app discovers the devices through mDNS (aka bonjour) by looking for services named "_wled._tcp."

Then, once a device is discovered, I call "/json/si" for its JSON api. You can read all about that API here:
https://kno.wled.ge/interfaces/json-api/


What kind of device are you trying to make work with my app? Is it a fork of WLED? I'd be happy to discuss more about it on Discord if you'd like.

**Comment by vortigont** [comment]
Oh! Thanks for the link! That's what I needed indeed! :)
My project is not a fork of WLED but a different app. It's a esp32 based "FireLamp" with various led effects running on ws2812 matrixes of arbitrary size and topology, also an experimental support for HUB75 panels is there. 
It has web interface working via websocket and appears pretty fine on your app actually. You can take a look here [FireLamp_JeeUI](https://github.com/vortigont/FireLamp_JeeUI).
I'm not using Discord that much, but can join a group from time to time.
